### ISSUE TITLE
Support multiple image names in the cmd line for the make cmd

### ISSUE THREAD

**Issue by alexro** [slicebuild/sb#10]
Handle multiple image names in the cmd like, like: "sb make jekyll, onemore, something" and process them from left to right as dependencies for the previous one. In the example:
jekyll will depend on onemore and onemore will depend on something.

The final layer should have all the slices requested.

**Comment by KalitaAlexey** [comment]
You said that final layer should have all the slices requested from all requested images, did I understand it right?
