### ISSUE TITLE
Support multiple image names for the find cmd

### ISSUE THREAD

**Issue by alexro** [slicebuild/sb#11]
When invoked "sb find jekyll, onemore, somethingelse" look for all the supplied names and output the images with the latest version for each of the name, like:

jekyll-3.0.0
onemore-1.2.3
somethingelse-0.3.1

**Comment by KalitaAlexey** [comment]
Is space after comma required?
Is space must be exactly one?

**Comment by KalitaAlexey** [comment]
I will do as many programs do without spaces. sb find Jekyll,onemore,somethingelse
