### ISSUE TITLE
Extend the find command to find similar images and missing dependencies at 2 levels

### ISSUE THREAD

**Issue by alexro** [slicebuild/sb#13]
slices:
  firstone - all deps are fine
  name1 - all deps are fine
  name2 - has a missing dep nameA
  name3 - has a missing dep nameX
  name4 - does not exist
  another-name4 - all deps are fine
  aname2 - all deps are fine

cmd: sb find name1,name2,name4

'find' builds up the list of all slices for a particular OS, then it finds all names that are similar to the requested ones (for now it checks that the requested name is part of a slice's name). It the reports the relative to the 'slices' dir path of the slice.

It also collects missing dependencies. 'find' looks at 2 levels: all slices and slices needed for the requested names.

Notice in the cmd name3 is not requested. But this slice has a missing dependency, so it should be reported at the first level (health of the whole registry)

'name2' exists but has a missing dep, 'name4' does not exist at all, These two should be reported at level 2 as needed to build the requested images.

output:

All Similar:
  /du/n/name1
  /du/n/name2
  /du/a/another-name4
  /du/a/aname2

All Missing:
  nameA,
  nameX
  name4

Found Requested:
  /du/n/name1
  /du/n/name2

Missing Requested:
  nameA
  name4

See: https://github.com/slicebuild/sb/blob/master/impl/mono/src/App/Commands/Find.cs

**Comment by KalitaAlexey** [comment]
"nameX" was not requested in find command. It is dependency. Should it be in "Missing requested" list?

**Comment by alexro** [comment]
No, should be nameA instead - dep of name2. Updated.

**Comment by KalitaAlexey** [comment]
What's the difference between "All missing" and "Missing requested"?

**Comment by alexro** [comment]
All Missing includes the ones that are a dependency of some slice not requested on the cmd.
This is a way to check the state of the whole registry. 

Another way to look at it if you use the cmd: sb find "all" - no need to implement that "all" param, it's just a metaphor

**Comment by KalitaAlexey** [comment]
How about to make command "check"? Or maybe command named "missing"
`sb missing`
And that is check.
That will be more intuitive.

**Comment by alexro** [comment]
This is basic thing - when you build the layers you can check for dependencies.
This logic is also reused in the make command, and possibly in other places.
That's why it doesn't make sense to create another command for that.

When I implemented it the code became much better and more concise. Is it difficult to do in rust?

**Comment by alexro** [comment]
Another thing is usability - it you start creating commands for every single action, the user will give up trying to learn all the rules. And you'll also have to make a manual, explaining when to do what. And don't worry, there will be more commands down the road.

**Comment by alexro** [comment]
If you want to rename find to check we can do it

**Comment by KalitaAlexey** [comment]
You got me wrong.

##### Clear intention

I mean when the user looks for some layers we can check dependencies for them. The user looks for specific layers and he probably wants to check dependencies of it. I mean it. But the user probably does not want to check dependencies of all registry. I suggest to add a new command "missing" to find all missing dependencies. It intuitive, it explicit.

##### Performance.

The user wants an answer as soon as possible.
Let the user executes
`sb find jekyll`
He expects to get information about jekyll right now. But instead of it the application checks all layers for missing dependencies. For huge registry it will be slow.

##### Extra output

The user wants to find jekyll. Let he has very huge registry and most of the layers have a missing dependency. Output will be very big and meaningless for the user.

**Comment by alexro** [comment]
Haha about not understanding each other! Double loss at both ends as we translate from English back to Russian :)

Anyway, your idea of user behavior is not real. There will be no missing deps most of the time. And no one wants to specifically 'check' for stuff. Usage patterns are different.

**Comment by KalitaAlexey** [comment]
Okey. I are more experienced than me. I will do as you want.

**Comment by alexro** [comment]
It's important to remember that the product design is not final. The focus should be making it flexible.

**Comment by KalitaAlexey** [comment]
What is the difference between All similar and found requested?
Let's assume we have the slices

```
aname
aname2
aname-1.0.0
```

Then command

```
sb find aname
```

Will outputs

```
All similar:
aname
aname2
aname-1.0.0
Found requested:
aname
aname-1.0.0
```

Am i right?

**Comment by alexro** [comment]
No, the difference is that for requested we get the specific version:

aname in the registry = aname-0.0.0, so only aname-1.0.0 will be returned, because by default we take the latest version of everything.

BUT if the requested was: aname-0.0.0 (specific version) then aname should be returned (this is for the next version when we deal with versions properly, but you can make it now if it's easier)

While 'similar', 'requested' and such may sound confusing, the point is not how to phrase it better - it can be changed later, the point is how to make it robust and ensure our internal logic is bullet-proof

**Comment by KalitaAlexey** [comment]
So. You mean output will be

```
All similar:
aname
aname2
aname-1.0.0
Found requested:
aname-1.0.0
```

Am I got you right?

**Comment by alexro** [comment]
Yes

**Comment by alexro** [comment]
there is a bug, found requested is wrong: 

./sb find apache

All similar:
du/a/apache/apache-2
du/l/lib/libapache2-mod-php5
All missing: None
Found requested: None
Missing requested: None

Also, please add lines between section for easier reading

EDIT: if not a easy fix, let's postpone it till next iteration when we fully implement versioning rules. I understand that currently the rules are a bit fuzzy.

**Comment by KalitaAlexey** [comment]
It's easy. I will fix it.

**Comment by alexro** [comment]
okay, any way I'm putting down all the rules we need to finally crack it. 24.10.2015, 06:39, "Alexey" notifications@github.com:It's easy. I will fix it.—Reply to this email directly or view it on GitHub.

**Comment by KalitaAlexey** [comment]
@alexro не понял.

**Comment by KalitaAlexey** [comment]
@alexro apache-2 in meaning of semver.org is invalid. It must be apache-2.0.0

**Comment by alexro** [comment]
apache == apache-0.0.0apache-1 == apache-1.0.0apache-1.2 == apache-1.2.0apache-2 == apache-2.0.0 we can ask people to do the job of computers and fix version in the file name, but good if the computer can do it instead 24.10.2015, 16:40, "Alexey" notifications@github.com:@alexro apache-2 in meaning of semver.org is invalid. It must be apache-2.0.0—Reply to this email directly or view it on GitHub.

**Comment by KalitaAlexey** [comment]
@alexro Can you promise me that there is no different packages which has similar names, except ending. For example
`package` and `package-2`.
If so, then I will fix it.
If not, then we may assume, but assumption in IT is bad.

**Comment by alexro** [comment]
In your example these are different versions of the same package:

apache == apache-0.0.0.0.0
apache-2 == apache-2.0.0.0.0

apache2 would be a dirfferent package == apache2-0.0.0.0.0

I've put down the rules finally: https://github.com/slicebuild/sb/blob/master/doc/slices-versioning.md
