### ISSUE TITLE
Formatter Factory is nonfunctional.

### ISSUE THREAD

**Issue by sezna** [slicebuild/sb#17]
I have some questions in the readme - basically, I'm not sure what the C# is doing when it returns the FormatterShell or FormatterDocker directly. Should I just call the write functions from those files directly?

**Comment by alexro** [comment]
At the time it isn't needed much and exists for future extensibility. You can do however you see fit.

You can read more about factory pattern here https://en.wikipedia.org/wiki/Factory_method_pattern

**Comment by sezna** [comment]
Awesome. Then I'm ready to merge the formatters branch - one thing, though. I couldn't test the imports because the module system was being weird, and it would help if Alexey looked over it as he is more familiar with the overall structure.

**Comment by alexro** [comment]
Thanks Alex!Please push up the new branch.Also, what was exact issue with the module system? 20.10.2015, 18:37, "Alex" notifications@github.com:Awesome. Then I'm ready to merge the formatters branch - one thing, though. I couldn't test the imports because the module system was being weird, and it would help if Alexey looked over it as he is more familiar with the overall structure.—Reply to this email directly or view it on GitHub.

**Comment by sezna** [comment]
I am just unfamiliar with the system so my compiler was throwing errors when I imported super::slice::{item, sections}. It should work with cargo building, however. I'd like Alexey to double check my imports and stuff, though, if that is okay.

**Comment by KalitaAlexey** [comment]
Dear @alexro, @sezna. When you want someone to see some issue. You can address them. Like I did with `@`. I will review formatters after I fix my own issues. Rust is messing with the wrong man.

**Comment by alexro** [comment]
Thanks @KalitaAlexey !

**Comment by alexro** [comment]
@sezna the line are joined incorrectly, should be empty line between RUN sections:

RUN apt-get update -y && \
apt-get install libc6-dev libssl-dev make build-essential libssl-dev libreadline6-dev zlib1g-dev libyaml-dev libz-dev -yRUN apt-get install -q -y ruby1.9.1RUN gem install jekyll -v '3.0.0.pre.beta9'

**Comment by sezna** [comment]
Ok, on it now. 

Alex

**Comment by alexro** [comment]
I haven't looked at the code so maybe you've already done it, the goal for docker formatter is to output every section other than OS and DEP.Only RUN commands should be joined together, others go "as is"In the end it should be a valid Dockerfile 24.10.2015, 01:07, "Alex" notifications@github.com:Ok, on it now.   Alex  > On Oct 23, 2015, at 6:53 PM, alexro notifications@github.com wrote: >  > @sezna the line are joined incorrectly, should be empty line between RUN sections: >  > RUN apt-get update -y && \ > apt-get install libc6-dev libssl-dev make build-essential libssl-dev libreadline6-dev zlib1g-dev libyaml-dev libz-dev -yRUN apt-get install -q -y ruby1.9.1RUN gem install jekyll -v '3.0.0.pre.beta9' >  > — > Reply to this email directly or view it on GitHub. > —Reply to this email directly or view it on GitHub.

**Comment by sezna** [comment]
It looks like @KalitaAlexey has fixed this on line 23 of docker_formatter
