### ISSUE TITLE
Read guidelines

### ISSUE THREAD

**Issue by KalitaAlexey** [slicebuild/sb#20]
We all must read https://github.com/rust-lang/rust/tree/master/src/doc/style
I just found first my style issue - _Prefer methods to functions if there is a clear receiver._

**Comment by alexro** [comment]
I definitely agree! I had a read through this a while back but have already forgotten most of it. I think it works if applied consistently on everyday basis.

**Comment by sezna** [comment]
Also, there's a package called rustfmt that I contribute to. It
auto-formats according to the guidelines, but it can be a little bit
glitchy, so you have to double check it. Point it at a mod.rs, lib.rs,
main.rs, etc. and it will format all submodules.
