### ISSUE TITLE
Does slice name may contains '-'?

### ISSUE THREAD

**Issue by KalitaAlexey** [slicebuild/sb#22]
Is it allowed to have slice with name `libsdl-ttf-2.0.0`? Or it must be libsdl_ttf-2.0.0?

**Comment by alexro** [comment]
Yes it can. Everything before dash+digit is a name. 25.10.2015, 11:44, "Alexey" notifications@github.com:Is it allowed to have slice with name libsdl-ttf-2.0.0? Or it must be libsdl_ttf-2.0.0?—Reply to this email directly or view it on GitHub.

**Comment by KalitaAlexey** [comment]
Is it allowed to have slice with name `libsdl-2-ttf-2.0.0`? Can I assume that if at some position in string there is dash+digit then all before it is name?

**Comment by alexro** [comment]
this will be invalid, libsdl is the name but the version parsing will crash.underscore will be fine: libsdl_2-ttf-2.0.0 or libsdl2-ttf-2.0.0  25.10.2015, 11:53, "Alexey" notifications@github.com:Is it allowed to have slice with name libsdl-2-ttf-2.0.0? Can I assume that if at some position in string there is dash+digit then all before it is name?—Reply to this email directly or view it on GitHub.

**Comment by KalitaAlexey** [comment]
Okey. Then I did it.
